version: '3.8'

services:
  api:
    build:
      context: ./Back/
      dockerfile: Clientes.Api/Dockerfile
    container_name: api
    ports:
      - "8090:8080"
      - "44379:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge